### ISSUE TITLE
Cursor chaining does not seem to work

### ISSUE THREAD

**Issue by benvanstaveren** [kraih/mango#1]
It seems chaining cursor commands doesn't work the same way it would in the "official" MongoDB driver, e.g.:

my $cursor = $coll->find({ ... })->sort({ ... })->limit(10); 

Results in no data being returned. If you do this:

my $cursor = $coll->find({ ... });
$cursor->sort({ ... });
$cursor->limit({ ... });

It works as expected. 

Not a super big deal but maybe worth mentioning in the docs :)

**Comment by kraih** [comment]
Those are just attributes, and they can almost certainly be chained.

**Comment by kraih** [comment]
There's even a unit test that covers your exact example. :) https://github.com/kraih/mango/blob/master/t/cursor.t#L42

**Comment by benvanstaveren** [comment]
Hum... that's really weird because when I chained a cursor and did a ->count 
it returned 0, when doing it one at a time, it returned the value I was 
expecting, not sure though I may have done something to the query between that 
to find out what was causing it... I'm low on my coffee so I may have been 
mistaken! :D

**Comment by marcusramberg** [comment]
Broken test or GTFO? ;-)

On Sun, Feb 17, 2013 at 2:49 AM, Ben van Staveren
notifications@github.comwrote:

> Hum... that's really weird because when I chained a cursor and did a
> ->count
> it returned 0, when doing it one at a time, it returned the value I was
> expecting, not sure though I may have done something to the query between
> that
> to find out what was causing it... I'm low on my coffee so I may have been
> mistaken! :D
> 
> On 02/17/2013 08:39 AM, Sebastian Riedel wrote:
> 
> > There's even a unit test that covers your exact example. :)
> > https://github.com/kraih/mango/blob/master/t/cursor.t#L42
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kraih/mango/issues/1#issuecomment-13678974.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kraih/mango/issues/1#issuecomment-13679078.

## 

---

Marcus Ramberg
Chief Yak Shaver
Nordaaker Consulting
+47-93417508

**Comment by benvanstaveren** [comment]
Tits!

Ehr, sorry wrong meme...

Test doesn't seem broken so I guess it was just me that was broken :)
