### ISSUE TITLE
feature req: mongoose like ODM enhancements

### ISSUE THREAD

**Issue by adam-stokes** [kraih/mango#10]
Hi,

Would love to see something like http://mongoosejs.com/ where we can define schema's with optional validation routines and extended attributes/methods on those defined models.

Thanks!

**Comment by marcusramberg** [comment]
I believe @jhthorsen's Mandel project aims to do this - https://github.com/jhthorsen/mandel

**Comment by adam-stokes** [comment]
awesome and thanks for the link!

**Comment by jhthorsen** [comment]
@battlemidget: Any feedback is more than welcome. (I'm batman in #mojo, btw)
