### ISSUE TITLE
MongoDB wire protocol version 2

### ISSUE THREAD

**Issue by kostyaten** [kraih/mango#12]
Problem!

my $mango = Mango->new('mongodb://localhost:27017');
my $db = $mango->db('test');
say dumper $db->collection_names();

MongoDB wire protocol version 2 required at /usr/share/perl5/Mango/Cursor.pm line 207.

MongoDB version 2.4.9

**Comment by kraih** [comment]
I'm afraid this is not a bug. http://mojolicio.us/perldoc/Mango#DESCRIPTION

**Comment by kraih** [comment]
I've changed the error message though. https://github.com/kraih/mango/commit/882d214d8586b197ae795af8c2edcd0d40c4469d
