### ISSUE TITLE
Mango::Cursor::_max logic error?

### ISSUE THREAD

**Issue by SailingYYC** [kraih/mango#16]
The current default for `batch_size` will always preclude using `limit` on a query and thus return all results to the cursor.

One must set both `batch_size` and `limit` on a cursor for either to take effect.

**Comment by kraih** [comment]
Please provide a test case, i'm unable to replicate the problem.

**Comment by SailingYYC** [comment]
Looking behind the interface, test case below, even when specifying `limit`, the server responds with up to 100 matching records.  This is quite costly as the average record size can be quite large.

`limit` is set to 5, `batch_size` defaults to 0, so `_max` results in 0.

``` perl
sub _max {
  my $self  = shift;
  my $limit = $self->limit;
  my $size  = $self->batch_size;
  return $limit == 0 || $size < $limit ? $size : $limit;
}
```

``` perl
use Mojolicious::Lite;
use Mango;
use Mango::BSON ':bson';

my $uri = 'mongodb://localhost/test';
helper mango => sub { state $mango = Mango->new($uri) };

# Store and retrieve information non-blocking
get '/' => sub {
  my $self = shift;

  my $collection = $self->mango->db->collection('nolimit');
  my $ip         = $self->tx->remote_address;

  # Store information about current visitor, 1000 times
  for (my $i = 0; $i <1000; $i++) {
    $collection->insert({when => bson_time, from => $ip});
  }

  $collection->find->sort({when => -1})->fields({_id => 0})->limit(5)->next(sub {
    my ($collection, $err, $doc) = @_;

    return $self->render_exception($err) if $err;

    # And show it to current visitor
    $self->render(json => { num_results => scalar @{$collection->{results}}, results => $collection->{results}, doc => $doc});
  });
};

app->start;
```

**Comment by kraih** [comment]
Thanks, fixed.

**Comment by kraih** [comment]
I'm sure it can be even smarter and only request the exact number of results required, but that is an exercise for another day. :wink:

**Comment by SailingYYC** [comment]
No thank you for your timely response and the phenomenal Mojolicious and Mango.  As I get more familiar with Mango I hope to actually provide the fixes as well.  I'll keep that exercise in mind, I have prior experience patching the official MongoDB driver.

If I may ask a quick question about Mango and iterating over a query results in a non-blocking manner? Is there a way to have each returned record processed in parallel via a callback? All I've really found is the recursive and sequential manner as you've used in `Cursor::all`.

**Comment by kraih** [comment]
No, there is no such functionality yet. I mostly follow the official node.js driver when it comes to non-blocking features, which i believe has a way to turn a cursor into an event emitter, which could be nice especially for tailable cursors, but i've not taken a closer look at it yet.
